### Site Settings ###
title               : Conor Wood Hayes
description         : >-
                      Hands on robotics & embedded systems engineer, 
                      working on robotic manipulation + embodied AI/ML, with deep experience 
                      building embedded systems for spacecraft and consumer medical devices.
baseurl             : ""            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : cwoodhayes/cwoodhayes.github.io
theme               : null
open_new_tab        : true                     # Opens external URLs in new tab (works for posts, projects and navbar only)

nav_subtitle        : Robotics + Embedded Systems

about:
  paragraph_1       : >-
    Hands-on robotics and embedded systems engineer with extensive experience 
    building & deploying real-world hardware, autonomy stacks, and mission-critical 
    embedded systems end-to-end. 
    Strong focus on systems design, field testing, and reliability in harsh environments.
  paragraph_2       : >-
    Currently studying for an MS in Robotics at Northwestern University, focusing on 
    robotic manipulation and embodied AI/ML. 


### Plugins ###
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/about.md
  - pages/blog.html
  - pages/cv.md


### Author Info ###
author:
  name              : Conor Hayes
  image             : /assets/prof_pics/lake_cheesin.jpg
  email             : cwhayes@u.northwestern.edu
  github            : cwoodhayes
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : cwoodhayes
  # medium            : your_username
  spotify           : 13DmASWA762GpdaSAAR90l
  twitter           : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - .vscode
